### ISSUE TITLE
有几个疑问

### ISSUE THREAD

**Issue by leslieeilsel** [hunzhiwange/queryphp#1]
1. What is Leevel?
2. 在执行完 composer install之后，出现如下错误。查看vendor目录确实无此包，然后进行手动安装（[包地址](https://github.com/doctrine/common)）。安装之后，发现还是报错，不知是不是包的问题？特地前来求助。
![微信截图_20181221114422.png](https://i.loli.net/2018/12/21/5c1c6381a2af6.png)

**Comment by doyouhaobaby** [comment]
1：Leevel 是单词 level 加入一个 e 新造的词，就如 swoole ,google 这些本来本不存在的单词。
代表着 QueryPHP 的愿景是写出有层次感的代码和理想追求，也是我们包管理的顶层命名空间，同时 Leevel 也是一个可选 PHP 扩展开发框架，可以与 QueryPHP 混用。

`Use Leevel\Database\Ddd\Entity;`

2：第二个我等哈检查哈，我最近加入 swoole 大改可能影响到 API，可能放开了最低依赖影响到的，晚上回去看看。
`https://github.com/hunzhiwange/framework/blob/master/.travis.yml#L40`
`- if [[ $setup = 'lowest' ]]; then travis_retry composer update doctrine/annotations ~1.6.0; fi`

**Comment by doyouhaobaby** [comment]
我的电脑 mac 安装后正常，我要看看 windows 安装后的问题，
**/data/codes/tests/myapp/vendor/composer/installed.json**

{
            "name": "doctrine/annotations",
            "version": "1.7.x-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/doctrine/annotations.git",
                "reference": "232c5da3903f788e02328b4e8486eceea0c76e58"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/doctrine/annotations/zipball/232c5da3903f788e02328b4e8486eceea0c76e58",
                "reference": "232c5da3903f788e02328b4e8486eceea0c76e58",
                "shasum": "",
                "mirrors": [
                    {
                        "url": "https://dl.laravel-china.org/%package%/%reference%.%type%",
                        "preferred": true
                    }
                ]
            },
            "require": {
                "doctrine/lexer": "1.*",
                "php": "^7.1"
            },
            "require-dev": {
                "doctrine/cache": "1.*",
                "phpunit/phpunit": "^7.0"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.7.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Doctrine\\Common\\Annotations\\": "lib/Doctrine/Common/Annotations"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Roman Borschel",
                    "email": "roman@code-factory.org"
                },
                {
                    "name": "Benjamin Eberlei",
                    "email": "kontakt@beberlei.de"
                },
                {
                    "name": "Guilherme Blanco",
                    "email": "guilhermeblanco@gmail.com"
                },
                {
                    "name": "Jonathan Wage",
                    "email": "jonwage@gmail.com"
                },
                {
                    "name": "Johannes Schmitt",
                    "email": "schmittjoh@gmail.com"
                }
            ],
            "description": "Docblock Annotations Parser",
            "homepage": "http://www.doctrine-project.org",
            "keywords": [
                "annotations",
                "docblock",
                "parser"
            ],
            "time": "2018-05-06T10:14:50+00:00"
        },

可以手动更新版本大于等于 1.6.0 
composer update doctrine/annotations ~1.6.0

**Comment by leslieeilsel** [comment]
谢谢提示，我一会试一下
