### ISSUE TITLE
对“USE LEEVEL DO BERTER”的疑问

### ISSUE THREAD

**Issue by Darknesser** [hunzhiwange/queryphp#3]
readme中logo上的"USE LEEVEL DO BERTER"是不是better打错了呀，还有leevel是什么含义呢？

**Comment by doyouhaobaby** [comment]
> readme中logo上的"USE LEEVEL DO BERTER"是不是better打错了呀，还有leevel是什么含义呢？

1：BERTER 打错，即将改正
2：Leevel 是单词 level 加入一个 e 新造的词，就如 Swoole ,google 这些本来本不存在的单词。
代表着 QueryPHP 的愿景是写出有层次感的代码和理想追求，具体表现就是不计成本的编写 3000 多测试用例，快 3 年还有几个月才发布第一个版本 V1.0.0 正式版，也是我们包管理的顶层命名空间，同时 Leevel 也是一个可选 PHP 扩展开发框架，将 QueryPHP 的核心用 zephir 语言编译成 C 实现的扩展。

Use Leevel\Database\Ddd\Entity;
