### ISSUE TITLE
安装基于什么环境都不知道 

### ISSUE THREAD

**Issue by dafa168** [hunzhiwange/queryphp#4]
php版本是多少？ 啥都不知道？

**Comment by twomiao** [comment]
> php版本是多少？ 啥都不知道？

> 文档安装地址：https://www.queryphp.com/docs/started/install.html#%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82
> 提醒：多看文档，这是Swoole框架系列里面写得最详细的了。
